---
apiVersion: v1 
kind: Service 
metadata: 
  annotations:   
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: 
        '{
            "type": "public",
            "bandwidth_name": "cce-bandwidth-3551163379627",
            "bandwidth_chargemode":"traffic",
            "bandwidth_size": 5,
            "bandwidth_sharetype": "PER",
            "eip_type": "5_bgp",
            "name": "james3"
        }'
  labels: 
    app: backend-ml 
  name: backend-ml 
spec: 
  ports: 
  - name: service2
    port: 8080
    protocol: TCP 
    targetPort: 8080
  selector: 
    app: backend-ml 
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ml
  template:
    metadata:
      labels:
        app: backend-ml
    spec:
      containers:
      - image: ninjavan-samuraiblue/backend-ml:v2
        name: backend-ml